services:
  forum:
    build: .
    container_name: forum
    ports:
      - "8080:8080"
    environment:
      - ADDR=:8080
      - DATABASE_URL=/data/forum.db
      - SESSION_LIFETIME_HOURS=24
    volumes:
      - forum_data:/data
      - ./web:/app/web:ro
      - ./schema.sql:/app/schema.sql:ro
volumes:
  forum_data:
